### ISSUE TITLE
Implement home page

### ISSUE THREAD

**Issue by imndaiga** [hippyhood/webiterate#14]

**Comment by aliaziz00** [comment]
To do:
- [x] Banner with logo.
- [x] Tag line below the logo.
- [ ] The journey components (what we are doing blurp).
- [ ] Explorer component.

Acceptance:
- [x] Each component must take the width and height of Page.
- [ ] Sticky scrolling.
- [ ] Include mission illustration/icons.
- [ ] Must link to the journey page.
- [ ] Must link to the explorer page.
