### ISSUE TITLE
Implement explorer page

### ISSUE THREAD

**Issue by imndaiga** [hippyhood/webiterate#16]
- [x] create quick wireframe for the showcase page
- [x] This page should give a brief intro the experiments
- [x] experiments should be show cased as a card and linked to
- [x] create placeholder experiment
- [x] create route for explorer page

**Comment by aliaziz00** [comment]
- [ ] Create route for explorer page

**Comment by aliaziz00** [comment]
- [x] create quick wireframe for the showcase page
- [ ] This page should give a brief intro the experiments
- [ ] experiments should be show cased as a card and linked to
- [ ] create placeholder experiment
